# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='mpas',
            field=models.ManyToManyField(blank=True, to='mpa.Mpa'),
        ),
    ]
