# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-25 13:40
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_squashed_0003_auto_20171106_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, editable=False, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='campaign',
            name='geom_smerc',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, editable=False, null=True, srid=3857),
        ),
        migrations.AddField(
            model_name='campaign',
            name='is_point',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='point_geom_smerc',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, editable=False, null=True, srid=3857),
        ),
        migrations.AddField(
            model_name='campaign',
            name='start_year',
            field=models.IntegerField(blank=True, choices=[(None, None), (1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018)], null=True, verbose_name='Start Year'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='point_geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, editable=False, null=True, srid=4326),
        ),
    ]
