# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 21:37
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_auto_20170213_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='categories',
            field=taggit.managers.TaggableManager(blank=True, help_text='You can assign this area to one or more categories by providing a comma-separated list of tags (e.g., [ Shark Sanctuary, World Heritage Site ]', through='category.TaggedItem', to='category.Category', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='country',
            field=models.CharField(max_length=20, verbose_name='Country / Territory'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='Campaign id'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(max_length=254, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='sub_location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sub Location'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='summary',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Campaign Description'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='Initiative id'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='name',
            field=models.CharField(max_length=254, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='summary',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Initiative Description'),
        ),
    ]
