# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-09 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_marinearea', models.FloatField(blank=True, null=True)),
                ('global_mpa', models.FloatField(blank=True, null=True)),
                ('global_strong', models.FloatField(blank=True, null=True)),
                ('global_notake', models.FloatField(blank=True, null=True)),
                ('global_unimplemented', models.FloatField(blank=True, null=True)),
                ('global_proposed', models.FloatField(blank=True, null=True)),
                ('eez_marinearea', models.FloatField(blank=True, null=True)),
                ('eez_mpa', models.FloatField(blank=True, null=True)),
                ('eez_strong', models.FloatField(blank=True, null=True)),
                ('eez_notake', models.FloatField(blank=True, null=True)),
                ('eez_unimplemented', models.FloatField(blank=True, null=True)),
                ('eez_proposed', models.FloatField(blank=True, null=True)),
                ('abnj_marinearea', models.FloatField(blank=True, null=True)),
                ('abnj_mpa', models.FloatField(blank=True, null=True)),
                ('abnj_strong', models.FloatField(blank=True, null=True)),
                ('abnj_notake', models.FloatField(blank=True, null=True)),
                ('abnj_unimplemented', models.FloatField(blank=True, null=True)),
                ('abnj_proposed', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
