DROP VIEW IF EXISTS public.mpa_assessment_geom_view CASCADE;

CREATE OR REPLACE VIEW public.mpa_assessment_geom_view
AS SELECT *
from assess.zoneassessment_export_view ze
LEFT OUTER JOIN 
	( select
		n.mpa_id as mpatlas_mpa_id,
		n.geom as mpatlas_geom,
		n.categories as mpatlas_categories,
		n.wdpa_id as mpatlas_wdpa_id,
		n.wdpa_pid as mpatlas_wdpa_pid,
    	n.usmpa_id as mpatlas_usmpa_id,
    	n.site_id as mpatlas_site_id,
    	n.name as mpatlas_name,
    	n.orig_name as mpatlas_orig_name,
    	n.long_name as mpatlas_long_name,
    	n.short_name as mpatlas_short_name,
    	n.slug as mpatlas_slug,
    	n.country as mpatlas_country,
    	n.sovereign as mpatlas_sovereign,
    	n.sub_location as mpatlas_sub_location,
    	n.designation as mpatlas_designation,
    	n.designation_eng as mpatlas_designation_eng,
    	n.designation_type as mpatlas_designation_type,
    	n.iucn_category as mpatlas_iucn_category,
    	n.int_criteria as mpatlas_int_criteria,
    	n.marine as mpatlas_marine,
    	n.status as mpatlas_status,
    	n.status_year as mpatlas_status_year,
    	n.is_mpa as mpatlas_is_mpa,
    	n.pa_def as mpatlas_pa_def,
    	n.implemented as mpatlas_implemented,
    	n.implementation_date as mpatlas_implementation_date,
    	n.no_take as mpatlas_no_take,
    	n.no_take_area as mpatlas_no_take_area,
    	n.rep_m_area as mpatlas_rep_m_area,
    	n.calc_m_area as mpatlas_calc_m_area,
    	n.rep_area as mpatlas_rep_area,
    	n.calc_area as mpatlas_calc_area,
    	n.gov_type as mpatlas_gov_type,
    	n.mgmt_auth as mpatlas_mgmt_auth,
    	n.own_type as mpatlas_own_type,
    	n.mgmt_plan_type as mpatlas_mgmt_plan_type,
    	n.mgmt_plan_ref as mpatlas_mgmt_plan_ref,
    	n.glores_status as mpatlas_glores_status,
    	n.conservation_effectiveness as mpatlas_conservation_effectiveness,
    	n.fishing as mpatlas_fishing,
    	n.fishing_info as mpatlas_fishing_info,
    	n.fishing_citation as mpatlas_fishing_citation,
    	n.access as mpatlas_access,
    	n.access_citation as mpatlas_access_citation,
    	n.primary_conservation_focus as mpatlas_primary_conservation_focus,
    	n.secondary_conservation_focus as mpatlas_secondary_conservation_focus,
    	n.tertiary_conservation_focus as mpatlas_tertiary_conservation_focus,
    	n.conservation_focus_citation as mpatlas_conservation_focus_citation,
    	n.protection_focus as mpatlas_protection_focus,
    	n.protection_focus_info as mpatlas_protection_focus_info,
    	n.protection_focus_citation as mpatlas_protection_focus_citation,
    	n.constancy as mpatlas_constancy,
    	n.constancy_citation as mpatlas_constancy_citation,
    	n.permanence as mpatlas_permanence,
    	n.permanence_citation as mpatlas_permanence_citation,
    	n.wdpa_notes as mpatlas_wdpa_notes,
    	n.notes as mpatlas_notes,
    	n.summary as mpatlas_summary,
    	n.is_point as mpatlas_is_point,
    	n.verification_state as mpatlas_verification_state,
    	n.verified_date as mpatlas_verified_date,
    	n.other_ids as mpatlas_other_ids,
    	n.verification_reason as mpatlas_verification_reason,
    	n.verified_by as mpatlas_verified_by,
    	n.verify_wdpa as mpatlas_verify_wdpa,
    	n.datasources as mpatlas_datasources,
    	n.conservation_focus_info as mpatlas_conservation_focus_info,
    	n.access_info as mpatlas_access_info,
    	n.cons_obj_wdpa as mpatlas_cons_obj_wdpa,
    	n.supp_info_wdpa as mpatlas_supp_info_wdpa,
    	n.fishing_protection_details as mpatlas_fishing_protection_details,
    	n.fishing_protection_level as mpatlas_fishing_protection_level,
    	n.protection_mpaguide_details as mpatlas_protection_mpaguide_details,
    	n.protection_mpaguide_level as mpatlas_protection_mpaguide_level,
    	n.protection_rbcs_details as mpatlas_protection_rbcs_details,
    	n.protection_rbcs_level as mpatlas_protection_rbcs_level,
    	n.protection_rbcs_level_name as mpatlas_protection_rbcs_level_name
           FROM public.mpa_category_view n) m
	ON (ze.mpa_zone_id = m.mpatlas_mpa_id);

-- Permissions

ALTER TABLE public.mpa_assessment_geom_view OWNER TO mpatlas;
GRANT ALL ON TABLE public.mpa_assessment_geom_view TO mpatlas;