# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='affiliation',
            field=models.CharField(blank=True, max_length=300, verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='title',
            field=models.CharField(choices=[('--', ''), ('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Miss', 'Miss'), ('Dr', 'Dr')], default='', max_length=200),
        ),
    ]
