# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 21:37
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='details',
            name='summary',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Short Summary'),
        ),
    ]
