# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import django.contrib.gis.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wdpa2014Point',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('wdpaid', models.IntegerField()),
                ('wdpa_pid', models.IntegerField()),
                ('name', models.CharField(max_length=254)),
                ('orig_name', models.CharField(max_length=254)),
                ('country', models.CharField(max_length=20)),
                ('sub_loc', models.CharField(max_length=100)),
                ('desig', models.CharField(max_length=254)),
                ('desig_eng', models.CharField(max_length=254)),
                ('desig_type', models.CharField(max_length=20)),
                ('iucn_cat', models.CharField(max_length=20)),
                ('int_crit', models.CharField(max_length=100)),
                ('marine', models.CharField(max_length=20)),
                ('rep_m_area', models.FloatField(null=True)),
                ('rep_area', models.FloatField(null=True)),
                ('status', models.CharField(max_length=100)),
                ('status_yr', models.IntegerField(null=True)),
                ('gov_type', models.CharField(max_length=254)),
                ('mang_auth', models.CharField(max_length=254)),
                ('mang_plan', models.CharField(max_length=254)),
                ('metadataid', models.IntegerField()),
                ('updateme', models.BooleanField(default=False)),
                ('new', models.BooleanField(default=False)),
                ('no_take', models.CharField(max_length=50)),
                ('no_tk_area', models.FloatField()),
                ('parent_iso3', models.CharField(max_length=100)),
                ('gis_area', models.FloatField(null=True)),
                ('gis_m_area', models.FloatField(null=True)),
                ('shape_leng', models.FloatField(default=0)),
                ('shape_area', models.FloatField(default=0)),
                ('geom_smerc', django.contrib.gis.db.models.fields.MultiPointField(srid=900913, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326, null=True)),
                ('geog', django.contrib.gis.db.models.fields.MultiPointField(srid=4326, null=True, geography=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Wdpa2014Polygon',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('wdpaid', models.IntegerField()),
                ('wdpa_pid', models.IntegerField()),
                ('name', models.CharField(max_length=254)),
                ('orig_name', models.CharField(max_length=254)),
                ('country', models.CharField(max_length=20)),
                ('sub_loc', models.CharField(max_length=100)),
                ('desig', models.CharField(max_length=254)),
                ('desig_eng', models.CharField(max_length=254)),
                ('desig_type', models.CharField(max_length=20)),
                ('iucn_cat', models.CharField(max_length=20)),
                ('int_crit', models.CharField(max_length=100)),
                ('marine', models.CharField(max_length=20)),
                ('rep_m_area', models.FloatField(null=True)),
                ('rep_area', models.FloatField(null=True)),
                ('status', models.CharField(max_length=100)),
                ('status_yr', models.IntegerField(null=True)),
                ('gov_type', models.CharField(max_length=254)),
                ('mang_auth', models.CharField(max_length=254)),
                ('mang_plan', models.CharField(max_length=254)),
                ('metadataid', models.IntegerField()),
                ('updateme', models.BooleanField(default=False)),
                ('new', models.BooleanField(default=False)),
                ('no_take', models.CharField(max_length=50)),
                ('no_tk_area', models.FloatField()),
                ('parent_iso3', models.CharField(max_length=100)),
                ('gis_area', models.FloatField(null=True)),
                ('gis_m_area', models.FloatField(null=True)),
                ('shape_leng', models.FloatField(default=0)),
                ('shape_area', models.FloatField(default=0)),
                ('geom_smerc', django.contrib.gis.db.models.fields.MultiPolygonField(srid=900913, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, null=True)),
                ('geog', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, null=True, geography=True)),
                ('point_within', django.contrib.gis.db.models.fields.PointField(srid=4326, null=True)),
                ('point_within_geojson', models.TextField(null=True)),
                ('bbox', django.contrib.gis.db.models.fields.PolygonField(srid=4326, null=True)),
                ('bbox_geojson', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='WdpaPoint',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('wdpaid', models.IntegerField()),
                ('wdpa_pid', models.IntegerField()),
                ('name', models.CharField(max_length=254)),
                ('orig_name', models.CharField(max_length=254)),
                ('country', models.CharField(max_length=20)),
                ('sub_loc', models.CharField(max_length=100)),
                ('desig', models.CharField(max_length=254)),
                ('desig_eng', models.CharField(max_length=254)),
                ('desig_type', models.CharField(max_length=20)),
                ('iucn_cat', models.CharField(max_length=20)),
                ('int_crit', models.CharField(max_length=100)),
                ('marine', models.CharField(max_length=20)),
                ('rep_m_area', models.FloatField(null=True)),
                ('rep_area', models.FloatField(null=True)),
                ('status', models.CharField(max_length=100)),
                ('status_yr', models.IntegerField(null=True)),
                ('gov_type', models.CharField(max_length=254)),
                ('mang_auth', models.CharField(max_length=254)),
                ('mang_plan', models.CharField(max_length=254)),
                ('metadataid', models.IntegerField()),
                ('objectid', models.IntegerField()),
                ('geom_smerc', django.contrib.gis.db.models.fields.MultiPointField(srid=900913, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326, null=True)),
                ('geog', django.contrib.gis.db.models.fields.MultiPointField(srid=4326, null=True, geography=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='WdpaPolygon',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('wdpaid', models.IntegerField()),
                ('wdpa_pid', models.IntegerField()),
                ('name', models.CharField(max_length=254)),
                ('orig_name', models.CharField(max_length=254)),
                ('country', models.CharField(max_length=20)),
                ('sub_loc', models.CharField(max_length=100)),
                ('desig', models.CharField(max_length=254)),
                ('desig_eng', models.CharField(max_length=254)),
                ('desig_type', models.CharField(max_length=20)),
                ('iucn_cat', models.CharField(max_length=20)),
                ('int_crit', models.CharField(max_length=100)),
                ('marine', models.CharField(max_length=20)),
                ('rep_m_area', models.FloatField(null=True)),
                ('rep_area', models.FloatField(null=True)),
                ('status', models.CharField(max_length=100)),
                ('status_yr', models.IntegerField(null=True)),
                ('gov_type', models.CharField(max_length=254)),
                ('mang_auth', models.CharField(max_length=254)),
                ('mang_plan', models.CharField(max_length=254)),
                ('metadataid', models.IntegerField()),
                ('objectid', models.IntegerField()),
                ('gis_area', models.FloatField(null=True)),
                ('gis_area_2', models.FloatField(default=0)),
                ('gis_m_area', models.FloatField(null=True)),
                ('difference', models.FloatField(default=0)),
                ('area_notes', models.CharField(max_length=250)),
                ('shape_leng', models.FloatField(default=0)),
                ('shape_area', models.FloatField(default=0)),
                ('geom_smerc', django.contrib.gis.db.models.fields.MultiPolygonField(srid=900913, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, null=True)),
                ('geog', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, null=True, geography=True)),
                ('point_within', django.contrib.gis.db.models.fields.PointField(srid=4326, null=True)),
                ('point_within_geojson', models.TextField(null=True)),
                ('bbox', django.contrib.gis.db.models.fields.PolygonField(srid=4326, null=True)),
                ('bbox_geojson', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
    ]
