# -*- coding: utf-8 -*-
from south.utils import datetime_utils as datetime
from south.db import db
from south.v2 import SchemaMigration
from django.db import models


class Migration(SchemaMigration):

    def forwards(self, orm):
        # Adding model 'Wdpa2014Polygon'
        db.create_table(u'wdpa_wdpa2014polygon', (
            (u'id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('wdpaid', self.gf('django.db.models.fields.IntegerField')()),
            ('wdpa_pid', self.gf('django.db.models.fields.IntegerField')()),
            ('name', self.gf('django.db.models.fields.CharField')(max_length=254)),
            ('orig_name', self.gf('django.db.models.fields.CharField')(max_length=254)),
            ('country', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('sub_loc', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('desig', self.gf('django.db.models.fields.CharField')(max_length=254)),
            ('desig_eng', self.gf('django.db.models.fields.CharField')(max_length=254)),
            ('desig_type', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('iucn_cat', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('int_crit', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('marine', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('rep_m_area', self.gf('django.db.models.fields.FloatField')(null=True)),
            ('rep_area', self.gf('django.db.models.fields.FloatField')(null=True)),
            ('status', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('status_yr', self.gf('django.db.models.fields.IntegerField')(null=True)),
            ('gov_type', self.gf('django.db.models.fields.CharField')(max_length=254)),
            ('mang_auth', self.gf('django.db.models.fields.CharField')(max_length=254)),
            ('mang_plan', self.gf('django.db.models.fields.CharField')(max_length=254)),
            ('metadataid', self.gf('django.db.models.fields.IntegerField')()),
            ('updateme', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('new', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('no_take', self.gf('django.db.models.fields.CharField')(max_length=50)),
            ('no_tk_area', self.gf('django.db.models.fields.FloatField')()),
            ('parent_iso3', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('gis_area', self.gf('django.db.models.fields.FloatField')(null=True)),
            ('gis_m_area', self.gf('django.db.models.fields.FloatField')(null=True)),
            ('shape_leng', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('shape_area', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('geom_smerc', self.gf('django.contrib.gis.db.models.fields.MultiPolygonField')(srid=900913, null=True)),
            ('geom', self.gf('django.contrib.gis.db.models.fields.MultiPolygonField')(null=True)),
            ('geog', self.gf('django.contrib.gis.db.models.fields.MultiPolygonField')(null=True, geography=True)),
            ('point_within', self.gf('django.contrib.gis.db.models.fields.PointField')(null=True)),
            ('point_within_geojson', self.gf('django.db.models.fields.TextField')(null=True)),
            ('bbox', self.gf('django.contrib.gis.db.models.fields.PolygonField')(null=True)),
            ('bbox_geojson', self.gf('django.db.models.fields.TextField')(null=True)),
        ))
        db.send_create_signal(u'wdpa', ['Wdpa2014Polygon'])

        # Adding model 'Wdpa2014Point'
        db.create_table(u'wdpa_wdpa2014point', (
            (u'id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('wdpaid', self.gf('django.db.models.fields.IntegerField')()),
            ('wdpa_pid', self.gf('django.db.models.fields.IntegerField')()),
            ('name', self.gf('django.db.models.fields.CharField')(max_length=254)),
            ('orig_name', self.gf('django.db.models.fields.CharField')(max_length=254)),
            ('country', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('sub_loc', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('desig', self.gf('django.db.models.fields.CharField')(max_length=254)),
            ('desig_eng', self.gf('django.db.models.fields.CharField')(max_length=254)),
            ('desig_type', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('iucn_cat', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('int_crit', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('marine', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('rep_m_area', self.gf('django.db.models.fields.FloatField')(null=True)),
            ('rep_area', self.gf('django.db.models.fields.FloatField')(null=True)),
            ('status', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('status_yr', self.gf('django.db.models.fields.IntegerField')(null=True)),
            ('gov_type', self.gf('django.db.models.fields.CharField')(max_length=254)),
            ('mang_auth', self.gf('django.db.models.fields.CharField')(max_length=254)),
            ('mang_plan', self.gf('django.db.models.fields.CharField')(max_length=254)),
            ('metadataid', self.gf('django.db.models.fields.IntegerField')()),
            ('updateme', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('new', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('no_take', self.gf('django.db.models.fields.CharField')(max_length=50)),
            ('no_tk_area', self.gf('django.db.models.fields.FloatField')()),
            ('parent_iso3', self.gf('django.db.models.fields.CharField')(max_length=100)),
            ('gis_area', self.gf('django.db.models.fields.FloatField')(null=True)),
            ('gis_m_area', self.gf('django.db.models.fields.FloatField')(null=True)),
            ('shape_leng', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('shape_area', self.gf('django.db.models.fields.FloatField')(default=0)),
            ('geom_smerc', self.gf('django.contrib.gis.db.models.fields.MultiPointField')(srid=900913, null=True)),
            ('geom', self.gf('django.contrib.gis.db.models.fields.MultiPointField')(null=True)),
            ('geog', self.gf('django.contrib.gis.db.models.fields.MultiPointField')(null=True, geography=True)),
        ))
        db.send_create_signal(u'wdpa', ['Wdpa2014Point'])


    def backwards(self, orm):
        # Deleting model 'Wdpa2014Polygon'
        db.delete_table(u'wdpa_wdpa2014polygon')

        # Deleting model 'Wdpa2014Point'
        db.delete_table(u'wdpa_wdpa2014point')


    models = {
        u'wdpa.wdpa2014point': {
            'Meta': {'object_name': 'Wdpa2014Point'},
            'country': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'desig': ('django.db.models.fields.CharField', [], {'max_length': '254'}),
            'desig_eng': ('django.db.models.fields.CharField', [], {'max_length': '254'}),
            'desig_type': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'geog': ('django.contrib.gis.db.models.fields.MultiPointField', [], {'null': 'True', 'geography': 'True'}),
            'geom': ('django.contrib.gis.db.models.fields.MultiPointField', [], {'null': 'True'}),
            'geom_smerc': ('django.contrib.gis.db.models.fields.MultiPointField', [], {'srid': '900913', 'null': 'True'}),
            'gis_area': ('django.db.models.fields.FloatField', [], {'null': 'True'}),
            'gis_m_area': ('django.db.models.fields.FloatField', [], {'null': 'True'}),
            'gov_type': ('django.db.models.fields.CharField', [], {'max_length': '254'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'int_crit': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'iucn_cat': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'mang_auth': ('django.db.models.fields.CharField', [], {'max_length': '254'}),
            'mang_plan': ('django.db.models.fields.CharField', [], {'max_length': '254'}),
            'marine': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'metadataid': ('django.db.models.fields.IntegerField', [], {}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '254'}),
            'new': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'no_take': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'no_tk_area': ('django.db.models.fields.FloatField', [], {}),
            'orig_name': ('django.db.models.fields.CharField', [], {'max_length': '254'}),
            'parent_iso3': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'rep_area': ('django.db.models.fields.FloatField', [], {'null': 'True'}),
            'rep_m_area': ('django.db.models.fields.FloatField', [], {'null': 'True'}),
            'shape_area': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'shape_leng': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'status': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'status_yr': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'sub_loc': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'updateme': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'wdpa_pid': ('django.db.models.fields.IntegerField', [], {}),
            'wdpaid': ('django.db.models.fields.IntegerField', [], {})
        },
        u'wdpa.wdpa2014polygon': {
            'Meta': {'object_name': 'Wdpa2014Polygon'},
            'bbox': ('django.contrib.gis.db.models.fields.PolygonField', [], {'null': 'True'}),
            'bbox_geojson': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'country': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'desig': ('django.db.models.fields.CharField', [], {'max_length': '254'}),
            'desig_eng': ('django.db.models.fields.CharField', [], {'max_length': '254'}),
            'desig_type': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'geog': ('django.contrib.gis.db.models.fields.MultiPolygonField', [], {'null': 'True', 'geography': 'True'}),
            'geom': ('django.contrib.gis.db.models.fields.MultiPolygonField', [], {'null': 'True'}),
            'geom_smerc': ('django.contrib.gis.db.models.fields.MultiPolygonField', [], {'srid': '900913', 'null': 'True'}),
            'gis_area': ('django.db.models.fields.FloatField', [], {'null': 'True'}),
            'gis_m_area': ('django.db.models.fields.FloatField', [], {'null': 'True'}),
            'gov_type': ('django.db.models.fields.CharField', [], {'max_length': '254'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'int_crit': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'iucn_cat': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'mang_auth': ('django.db.models.fields.CharField', [], {'max_length': '254'}),
            'mang_plan': ('django.db.models.fields.CharField', [], {'max_length': '254'}),
            'marine': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'metadataid': ('django.db.models.fields.IntegerField', [], {}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '254'}),
            'new': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'no_take': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'no_tk_area': ('django.db.models.fields.FloatField', [], {}),
            'orig_name': ('django.db.models.fields.CharField', [], {'max_length': '254'}),
            'parent_iso3': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'point_within': ('django.contrib.gis.db.models.fields.PointField', [], {'null': 'True'}),
            'point_within_geojson': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'rep_area': ('django.db.models.fields.FloatField', [], {'null': 'True'}),
            'rep_m_area': ('django.db.models.fields.FloatField', [], {'null': 'True'}),
            'shape_area': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'shape_leng': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'status': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'status_yr': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'sub_loc': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'updateme': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'wdpa_pid': ('django.db.models.fields.IntegerField', [], {}),
            'wdpaid': ('django.db.models.fields.IntegerField', [], {})
        },
        u'wdpa.wdpapoint': {
            'Meta': {'object_name': 'WdpaPoint'},
            'country': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'desig': ('django.db.models.fields.CharField', [], {'max_length': '254'}),
            'desig_eng': ('django.db.models.fields.CharField', [], {'max_length': '254'}),
            'desig_type': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'geog': ('django.contrib.gis.db.models.fields.MultiPointField', [], {'null': 'True', 'geography': 'True'}),
            'geom': ('django.contrib.gis.db.models.fields.MultiPointField', [], {'null': 'True'}),
            'geom_smerc': ('django.contrib.gis.db.models.fields.MultiPointField', [], {'srid': '900913', 'null': 'True'}),
            'gov_type': ('django.db.models.fields.CharField', [], {'max_length': '254'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'int_crit': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'iucn_cat': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'mang_auth': ('django.db.models.fields.CharField', [], {'max_length': '254'}),
            'mang_plan': ('django.db.models.fields.CharField', [], {'max_length': '254'}),
            'marine': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'metadataid': ('django.db.models.fields.IntegerField', [], {}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '254'}),
            'objectid': ('django.db.models.fields.IntegerField', [], {}),
            'orig_name': ('django.db.models.fields.CharField', [], {'max_length': '254'}),
            'rep_area': ('django.db.models.fields.FloatField', [], {'null': 'True'}),
            'rep_m_area': ('django.db.models.fields.FloatField', [], {'null': 'True'}),
            'status': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'status_yr': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'sub_loc': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'wdpa_pid': ('django.db.models.fields.IntegerField', [], {}),
            'wdpaid': ('django.db.models.fields.IntegerField', [], {})
        },
        u'wdpa.wdpapolygon': {
            'Meta': {'object_name': 'WdpaPolygon'},
            'area_notes': ('django.db.models.fields.CharField', [], {'max_length': '250'}),
            'bbox': ('django.contrib.gis.db.models.fields.PolygonField', [], {'null': 'True'}),
            'bbox_geojson': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'country': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'desig': ('django.db.models.fields.CharField', [], {'max_length': '254'}),
            'desig_eng': ('django.db.models.fields.CharField', [], {'max_length': '254'}),
            'desig_type': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'difference': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'geog': ('django.contrib.gis.db.models.fields.MultiPolygonField', [], {'null': 'True', 'geography': 'True'}),
            'geom': ('django.contrib.gis.db.models.fields.MultiPolygonField', [], {'null': 'True'}),
            'geom_smerc': ('django.contrib.gis.db.models.fields.MultiPolygonField', [], {'srid': '900913', 'null': 'True'}),
            'gis_area': ('django.db.models.fields.FloatField', [], {'null': 'True'}),
            'gis_area_2': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'gis_m_area': ('django.db.models.fields.FloatField', [], {'null': 'True'}),
            'gov_type': ('django.db.models.fields.CharField', [], {'max_length': '254'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'int_crit': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'iucn_cat': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'mang_auth': ('django.db.models.fields.CharField', [], {'max_length': '254'}),
            'mang_plan': ('django.db.models.fields.CharField', [], {'max_length': '254'}),
            'marine': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'metadataid': ('django.db.models.fields.IntegerField', [], {}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '254'}),
            'objectid': ('django.db.models.fields.IntegerField', [], {}),
            'orig_name': ('django.db.models.fields.CharField', [], {'max_length': '254'}),
            'point_within': ('django.contrib.gis.db.models.fields.PointField', [], {'null': 'True'}),
            'point_within_geojson': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'rep_area': ('django.db.models.fields.FloatField', [], {'null': 'True'}),
            'rep_m_area': ('django.db.models.fields.FloatField', [], {'null': 'True'}),
            'shape_area': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'shape_leng': ('django.db.models.fields.FloatField', [], {'default': '0'}),
            'status': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'status_yr': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'sub_loc': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'wdpa_pid': ('django.db.models.fields.IntegerField', [], {}),
            'wdpaid': ('django.db.models.fields.IntegerField', [], {})
        }
    }

    complete_apps = ['wdpa']