# Generated by Django 2.2.15 on 2020-12-18 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wdpa', '0004_auto_20201218_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wdpasource',
            name='verifier',
        ),
    ]
