# Generated by Django 2.2.15 on 2020-12-19 14:21

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wdpa', '0005_remove_wdpasource_verifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wdpa2020point',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPointField(null=True, srid=4326),
        ),
    ]
