# Generated by Django 2.2.17 on 2020-12-21 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wdpa', '0006_auto_20201219_1421'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wdpa2020Point',
            new_name='WdpaPoint_new',
        ),
        migrations.RenameModel(
            old_name='WdpaPoint',
            new_name='WdpaPoint_old',
        ),
        migrations.RenameModel(
            old_name='Wdpa2019Point',
            new_name='WdpaPoint_prev',
        ),
        migrations.RenameModel(
            old_name='Wdpa2020Poly',
            new_name='WdpaPoly_new',
        ),
        migrations.RenameModel(
            old_name='Wdpa2019Poly',
            new_name='WdpaPoly_prev',
        ),
        migrations.RenameModel(
            old_name='WdpaPolygon',
            new_name='WdpaPolygon_old',
        ),
    ]
