# Generated by Django 3.1.7 on 2022-07-19 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wdpa', '0008_auto_20201221_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wdpasource',
            name='disclaimer',
            field=models.CharField(max_length=264, null=True),
        ),
    ]
