# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 12:25
from __future__ import unicode_literals

import bootstrap_layout.models
from django.db import migrations, models
import django.db.models.deletion
import djangocms_attributes_field.fields
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('filer', '0007_auto_20161016_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='bootstrap_layout_section', serialize=False, to='cms.CMSPlugin')),
                ('name', models.CharField(blank=True, default='', help_text='Descriptive name [not rendered on page]', max_length=25, null=True, verbose_name='Section Name')),
                ('min_height', models.CharField(default='0px', help_text='0 is default. Set it larger to expand height of section.', max_length=25, verbose_name='Minimum Section Height')),
                ('bg_color', models.CharField(default='transparent', help_text='(e.g., #RRGGBB, rgba(120,120,120,0.3))', max_length=25, verbose_name='CSS Background Color')),
                ('bg_size', models.CharField(choices=[('100% auto', 'fit width: 100% auto'), ('auto 100%', 'fit height: auto 100%'), ('cover', 'fill: cover '), ('auto', 'default: auto')], default='cover', max_length=25, verbose_name='Background Size')),
                ('bg_position', models.CharField(blank=True, default='center', max_length=25, verbose_name='Background Position')),
                ('bg_repeat', models.CharField(blank=True, choices=[('no-repeat', 'no-repeat'), ('repeat', 'repeat'), ('repeat-x', 'repeat-x'), ('repeat-y', 'repeat-y')], default='no-repeat', max_length=25, verbose_name='Background Repeat')),
                ('bg_attachment', models.CharField(blank=True, choices=[('scroll', 'scroll'), ('fixed', 'fixed')], default='scroll', max_length=25, verbose_name='Background Attachment')),
                ('container', models.CharField(choices=[('', 'No container (full-width)'), ('container', '.container (smaller content width based on device size)'), ('container-fluid', '.container-fluid (full-width with slight padding on sides)')], default='.container', help_text='Adds a ".container" or ".container-fluid" element inside the section', max_length=25, verbose_name='Add .container element or .container-fluid')),
                ('classes', bootstrap_layout.models.Classes(blank=True, default='', help_text='Space separated classes that are added to the class. See <a href="http://getbootstrap.com/css/" target="_blank">Bootstrap 3 documentation</a>.', verbose_name='Classes')),
                ('attributes', djangocms_attributes_field.fields.AttributesField(blank=True, default=dict, verbose_name='Attributes')),
                ('bg_image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
