# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap_layout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Descriptive name [not rendered on page]', max_length=25, null=True, verbose_name='Section Name'),
        ),
        migrations.AlterField(
            model_name='section',
            name='bg_size',
            field=models.CharField(choices=[('100% auto', 'fit width: 100% auto'), ('auto 100%', 'fit height: auto 100%'), ('cover', 'fill: cover '), ('auto', 'default: auto')], default='cover', max_length=25, verbose_name='Background Size'),
        ),
    ]
