# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap_layout', '0002_auto_20170213_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='container',
            field=models.CharField(blank=True, choices=[('.container', 'scroll'), ('.container-fluid', 'fixed'), ('', 'No container')], default='', help_text='Adds a ".container" or ".container-fluid" element inside the section', max_length=25, verbose_name='Add .container element or .container-fluid'),
        ),
    ]
