# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 12:04
from __future__ import unicode_literals

from django.db import migrations

def container_merge(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Section = apps.get_model("bootstrap_layout", "Section")
    for section in Section.objects.all():
        section.container = 'container' if section.add_container else ''
        section.save()

class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap_layout', '0003_section_container'),
    ]

    operations = [
        migrations.RunPython(container_merge),
    ]
