# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap_layout', '0004_auto_20170321_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='add_container',
        ),
        migrations.AlterField(
            model_name='section',
            name='container',
            field=models.CharField(choices=[('', 'No container (full-width)'), ('container', '.container (smaller content width based on device size)'), ('container-fluid', '.container-fluid (full-width with slight padding on sides)')], default='.container', help_text='Adds a ".container" or ".container-fluid" element inside the section', max_length=25, verbose_name='Add .container element or .container-fluid'),
        ),
    ]
