# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 12:19
from __future__ import unicode_literals

import ckeditor.fields
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    
    initial = True

    dependencies = [
        ('mpa', '0001_squashed_0006_auto_20171106_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eez',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eez', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('objectid', models.IntegerField()),
                ('sovereign', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=150)),
                ('sov_id', models.IntegerField()),
                ('iso_3digit', models.CharField(max_length=50)),
                ('gazid', models.FloatField()),
                ('eez_id', models.IntegerField()),
                ('area', models.FloatField()),
                ('geom_smerc', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=3857)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
                ('geog', django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, null=True, srid=4326)),
                ('simple_geom_smerc', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=3857)),
                ('simple_geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
                ('simple_geog', django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='EezMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_in_eez', models.FloatField(null=True, verbose_name='mpa area in eez (m2)')),
                ('eez', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spatialdata.Eez')),
                ('mpa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mpa.Mpa')),
            ],
        ),
        migrations.CreateModel(
            name='Meow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecoregion_code', models.FloatField()),
                ('ecoregion', models.CharField(max_length=50)),
                ('province_code', models.FloatField()),
                ('province', models.CharField(max_length=40)),
                ('realm_code', models.FloatField()),
                ('realm', models.CharField(max_length=40)),
                ('alt_code', models.FloatField()),
                ('ecoregion_code_x', models.FloatField()),
                ('latitude_zone', models.CharField(max_length=10)),
                ('geom_smerc', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=3857)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
                ('geog', django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, null=True, srid=4326)),
                ('simple_geom_smerc', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=3857)),
                ('simple_geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
                ('simple_geog', django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('iso3code', models.CharField(default='', max_length=3)),
                ('summary', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Nation Protection Summary')),
                ('marine_area', models.FloatField(blank=True, null=True)),
                ('mpa_area', models.FloatField(blank=True, null=True)),
                ('mpa_percent', models.FloatField(blank=True, null=True)),
                ('notake_area', models.FloatField(blank=True, null=True)),
                ('notake_percent', models.FloatField(blank=True, null=True)),
                ('geom_smerc', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=3857)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
                ('geog', django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, null=True, srid=4326)),
                ('simple_geom_smerc', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=3857)),
                ('simple_geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
                ('simple_geog', django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, null=True, srid=4326)),
                ('mpa_agency', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='National Marine Protected Area Agency')),
            ],
        ),
        migrations.AddField(
            model_name='eez',
            name='mpas',
            field=models.ManyToManyField(through='spatialdata.EezMembership', to='mpa.Mpa', verbose_name='MPAs within this EEZ'),
        ),
        migrations.AddField(
            model_name='eez',
            name='nation',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='spatialdata.Nation'),
        ),
    ]
