# Generated by Django 2.0.2 on 2018-02-13 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spatialdata', '0001_squashed_0003_auto_20171106_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eez',
            name='nation',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spatialdata.Nation'),
        ),
    ]
