# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 21:37
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatialdata', '0002_nation_mpa_agency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eez',
            name='mpas',
            field=models.ManyToManyField(through='spatialdata.EezMembership', to='mpa.Mpa', verbose_name='MPAs within this EEZ'),
        ),
        migrations.AlterField(
            model_name='eezmembership',
            name='area_in_eez',
            field=models.FloatField(null=True, verbose_name='mpa area in eez (m2)'),
        ),
        migrations.AlterField(
            model_name='nation',
            name='iso3code',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='nation',
            name='mpa_agency',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='National Marine Protected Area Agency'),
        ),
        migrations.AlterField(
            model_name='nation',
            name='summary',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Nation Protection Summary'),
        ),
    ]
