# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-18 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatialdata', '0002_auto_20180213_0214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nation',
            name='mpa_area',
        ),
        migrations.RemoveField(
            model_name='nation',
            name='mpa_percent',
        ),
        migrations.RemoveField(
            model_name='nation',
            name='notake_area',
        ),
        migrations.RemoveField(
            model_name='nation',
            name='notake_percent',
        ),
        migrations.AddField(
            model_name='nation',
            name='implemented_highmpa_area',
            field=models.FloatField(blank=True, null=True, verbose_name='Implemented Highly Protected MPA Area'),
        ),
        migrations.AddField(
            model_name='nation',
            name='implemented_mpa_area',
            field=models.FloatField(blank=True, null=True, verbose_name='Implemented MPA Area'),
        ),
        migrations.AddField(
            model_name='nation',
            name='implemented_notake_area',
            field=models.FloatField(blank=True, null=True, verbose_name='Implemented No-Take Reserve Area'),
        ),
        migrations.AddField(
            model_name='nation',
            name='proposed_highmpa_area',
            field=models.FloatField(blank=True, null=True, verbose_name='Known Proposed Highly Protected MPA Area'),
        ),
        migrations.AddField(
            model_name='nation',
            name='proposed_mpa_area',
            field=models.FloatField(blank=True, null=True, verbose_name='Known Proposed MPA Area'),
        ),
        migrations.AddField(
            model_name='nation',
            name='proposed_notake_area',
            field=models.FloatField(blank=True, null=True, verbose_name='Known Proposed No-Take Reserve Area'),
        ),
        migrations.AddField(
            model_name='nation',
            name='unimplemented_highmpa_area',
            field=models.FloatField(blank=True, null=True, verbose_name='Unimplemented Highly Protected MPA Area'),
        ),
        migrations.AddField(
            model_name='nation',
            name='unimplemented_mpa_area',
            field=models.FloatField(blank=True, null=True, verbose_name='Unimplemented MPA Area'),
        ),
        migrations.AddField(
            model_name='nation',
            name='unimplemented_notake_area',
            field=models.FloatField(blank=True, null=True, verbose_name='Unimplemented No-Take Reserve Area'),
        ),
    ]
