# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpa',
            name='other_contacts',
            field=models.ManyToManyField(blank=True, to='mpa.Contact', verbose_name=b'Other Contacts'),
        ),
    ]
