# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-10 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mpa', '0003_auto_20170710_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpa',
            name='datasource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mpa_datasources', to='mpa.DataSource', verbose_name=b'Data Source'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='version',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name=b'Version or Access Date'),
        ),
    ]
