# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-08 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpa', '0004_auto_20170710_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpa',
            name='glores_status',
            field=models.CharField(blank=True, choices=[(b'', b'None'), (b'nominee', b'Nominee'), (b'platinum', b'Platinum Award'), (b'gold', b'Gold Award'), (b'silver', b'Silver Award')], default=b'', max_length=100, verbose_name=b'GLORES Status'),
        ),
    ]
