# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 21:35
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('mpa', '0005_mpa_glores_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateinfo',
            name='scope',
            field=models.CharField(blank=True, choices=[('Site', 'Site'), ('Seascape', 'Seascape')], default='Site', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='candidateinfo',
            name='summary',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Candidate MPA Summary Description'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Data Source Name'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Data Source URL'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='version',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Version or Access Date'),
        ),
        migrations.AlterField(
            model_name='mpa',
            name='access',
            field=models.CharField(blank=True, choices=[('Unknown', 'Unknown'), ('Yes', 'Yes'), ('No', 'No'), ('Restricted', 'Restricted')], default='Unknown', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='mpa',
            name='categories',
            field=taggit.managers.TaggableManager(blank=True, help_text='You can assign this area to one or more categories by providing a comma-separated list of tags enclosed in quotes (e.g., [ "Shark Sanctuary", "World Heritage Site" ]', through='category.TaggedItem', to='category.Category', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='mpa',
            name='conservation_effectiveness',
            field=models.CharField(blank=True, choices=[('Unknown', 'Unknown'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Unknown', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='mpa',
            name='constancy',
            field=models.CharField(blank=True, choices=[('Unknown', 'Unknown'), ('Year-round', 'Year-round'), ('Seasonal', 'Seasonal'), ('Temporary', 'Temporary')], default='Unknown', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='mpa',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mpa_main_set', to='mpa.Contact', verbose_name='Main Contact'),
        ),
        migrations.AlterField(
            model_name='mpa',
            name='country',
            field=models.CharField(max_length=50, verbose_name='Country / Territory'),
        ),
        migrations.AlterField(
            model_name='mpa',
            name='datasource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mpa_datasources', to='mpa.DataSource', verbose_name='Data Source'),
        ),
        migrations.AlterField(
            model_name='mpa',
            name='designation',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Designation'),
        ),
        migrations.AlterField(
            model_name='mpa',
            name='designation_eng',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='English Designation'),
        ),
        migrations.AlterField(
            model_name='mpa',
            name='designation_type',
            field=models.CharField(blank=True, choices=[('National', 'National'), ('International', 'International')], max_length=20, null=True, verbose_name='Designation Type'),
        ),
        migrations.AlterField(
            model_name='mpa',
            name='fishing',
            field=models.CharField(blank=True, choices=[('Unknown', 'Unknown'), ('Yes', 'Yes'), ('No', 'No'), ('Some Restrictions', 'Some Restrictions')], default='Unknown', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='mpa',
            name='glores_status',
            field=models.CharField(blank=True, choices=[('', 'None'), ('nominee', 'Nominee'), ('platinum', 'Platinum Award'), ('gold', 'Gold Award'), ('silver', 'Silver Award')], default='', max_length=100, verbose_name='GLORES Status'),
        ),
        migrations.AlterField(
            model_name='mpa',
            name='gov_type',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Governance Type'),
        ),
        migrations.AlterField(
            model_name='mpa',
            name='implementation_date',
            field=models.DateField(blank=True, help_text='Date regulations went into effect or will go into effect', null=True, verbose_name='Implementation Date'),
        ),
        migrations.AlterField(
            model_name='mpa',
            name='implemented',
            field=models.BooleanField(default=True, help_text='MPA is designated and implemented with regulations enforced', verbose_name='Implemented?'),
        ),
        migrations.AlterField(
            model_name='mpa',
            name='int_criteria',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='International Criteria'),
        ),
        migrations.AlterField(
            model_name='mpa',
            name='iucn_category',
            field=models.CharField(blank=True, choices=[('Ia', 'Ia'), ('Ib', 'Ib'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI')], max_length=20, null=True, verbose_name='IUCN Category'),
        ),
        migrations.AlterField(
            model_name='mpa',
            name='marine',
            field=models.NullBooleanField(default=True, editable=False, verbose_name='Marine (field from WDPA)'),
        ),
        migrations.AlterField(
            model_name='mpa',
            name='mgmt_auth',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Management Authority'),
        ),
        migrations.AlterField(
            model_name='mpa',
            name='mgmt_plan_ref',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Management Plan Reference'),
        ),
        migrations.AlterField(
            model_name='mpa',
            name='mgmt_plan_type',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Management Plan Type'),
        ),
        migrations.AlterField(
            model_name='mpa',
            name='mpa_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='MPA id'),
        ),
        migrations.AlterField(
            model_name='mpa',
            name='name',
            field=models.CharField(help_text='Protected area name not including designation title', max_length=254, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='mpa',
            name='no_take',
            field=models.CharField(choices=[('None', 'None'), ('Part', 'Part'), ('All', 'All'), ('Not Reported', 'Not Reported')], default='Not Reported', max_length=100, verbose_name='No Take'),
        ),
        migrations.AlterField(
            model_name='mpa',
            name='notes',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Area Notes'),
        ),
        migrations.AlterField(
            model_name='mpa',
            name='other_contacts',
            field=models.ManyToManyField(blank=True, to='mpa.Contact', verbose_name='Other Contacts'),
        ),
        migrations.AlterField(
            model_name='mpa',
            name='other_ids',
            field=models.CharField(blank=True, help_text='ID codes used by other groups to identify this area, e.g., TNC Caribbean or Coral Triangle Atlas ids.', max_length=1000, null=True, verbose_name='Other reference id codes'),
        ),
        migrations.AlterField(
            model_name='mpa',
            name='permanence',
            field=models.CharField(blank=True, choices=[('Unknown', 'Unknown'), ('Permanent', 'Permanent'), ('Non-Permanent', 'Non-Permanent'), ('Non-Permanent - Conditional', 'Non-Permanent - Conditional'), ('Non-Permanent - Temporary', 'Non-Permanent - Temporary')], default='Unknown', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='mpa',
            name='primary_conservation_focus',
            field=models.CharField(blank=True, choices=[('Unknown', 'Unknown'), ('Biodiversity Protection', 'Biodiversity Protection'), ('Biomass Enhancement', 'Biomass Enhancement'), ('Cultural Heritage', 'Cultural Heritage')], default='Unknown', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='mpa',
            name='protection_focus',
            field=models.CharField(blank=True, choices=[('Unknown', 'Unknown'), ('Ecosystem', 'Ecosystem'), ('Focal Species', 'Focal Species')], default='Unknown', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='mpa',
            name='protection_level',
            field=models.CharField(blank=True, choices=[('Unknown', 'Unknown'), ('Strongly Protected', 'Strongly Protected'), ('Moderately Protected', 'Moderately Protected'), ('Protected', 'Protected'), ('Managed', 'Managed')], default='Unknown', editable=False, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='mpa',
            name='secondary_conservation_focus',
            field=models.CharField(blank=True, choices=[('Unknown', 'Unknown'), ('Biodiversity Protection', 'Biodiversity Protection'), ('Biomass Enhancement', 'Biomass Enhancement'), ('Cultural Heritage', 'Cultural Heritage')], default='Unknown', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='mpa',
            name='short_name',
            field=models.CharField(blank=True, help_text='Nickname if any', max_length=254),
        ),
        migrations.AlterField(
            model_name='mpa',
            name='sovereign',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sovereign Country'),
        ),
        migrations.AlterField(
            model_name='mpa',
            name='status',
            field=models.CharField(blank=True, choices=[('Proposed', 'Proposed'), ('Designated', 'Designated'), ('Defunct/Degazetted', 'Defunct/Degazetted')], default='Designated', max_length=100, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='mpa',
            name='status_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Status Year'),
        ),
        migrations.AlterField(
            model_name='mpa',
            name='sub_location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sub Location'),
        ),
        migrations.AlterField(
            model_name='mpa',
            name='summary',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='MPA Summary Site Description'),
        ),
        migrations.AlterField(
            model_name='mpa',
            name='tertiary_conservation_focus',
            field=models.CharField(blank=True, choices=[('Unknown', 'Unknown'), ('Biodiversity Protection', 'Biodiversity Protection'), ('Biomass Enhancement', 'Biomass Enhancement'), ('Cultural Heritage', 'Cultural Heritage')], default='Unknown', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='mpa',
            name='usmpa_id',
            field=models.CharField(blank=True, help_text='US NOAA MPA Center ID. You probably should not be changing this.', max_length=50, null=True, verbose_name='US MPA id'),
        ),
        migrations.AlterField(
            model_name='mpa',
            name='verification_reason',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Verification Reason'),
        ),
        migrations.AlterField(
            model_name='mpa',
            name='verification_state',
            field=models.CharField(choices=[('Unverified', 'Unverified'), ('Cannot Verify', 'Cannot Verify'), ('Rejected as MPA', 'Rejected as MPA'), ('Internally Verified', 'Internally Verified'), ('Externally Verified', 'Externally Verified')], default='Unverified', max_length=100, verbose_name='Verification State'),
        ),
        migrations.AlterField(
            model_name='mpa',
            name='verified_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Verified By'),
        ),
        migrations.AlterField(
            model_name='mpa',
            name='verified_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date Verified'),
        ),
        migrations.AlterField(
            model_name='mpa',
            name='wdpa_id',
            field=models.IntegerField(blank=True, help_text='WDPA ID code. You probably should not be changing this.', null=True, verbose_name='WDPA id'),
        ),
        migrations.AlterField(
            model_name='mpa',
            name='wdpa_notes',
            field=models.CharField(blank=True, editable=False, max_length=250, null=True, verbose_name='Area Notes (from WDPA)'),
        ),
        migrations.AlterField(
            model_name='wikiarticle',
            name='summary',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='MPA Site Description from Wikipedia'),
        ),
        migrations.AlterField(
            model_name='wikiarticle',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Link to Wikipedia Article'),
        ),
    ]
