# -*- coding: utf-8 -*-
# Generated by russmo 2017-11-08
from __future__ import unicode_literals

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('mpa', '0001_squashed_0006_auto_20171106_2135'),
        ('postgres_search_extensions', '0001_initial')
    ]

    operations = [
        migrations.RunSQL([
            '''CREATE INDEX idx_fts_mpa_name ON mpa_mpa USING gin( 
                (
                    to_tsvector('english_unaccent'::regconfig, COALESCE("mpa_mpa"."name", ''))
                    || to_tsvector('english_unaccent'::regconfig, COALESCE("mpa_mpa"."designation", ''))
                    || to_tsvector('english_unaccent'::regconfig, COALESCE("mpa_mpa"."designation_eng", '')) 
                ),
                (
                    to_tsvector('simple_unaccent'::regconfig, COALESCE("mpa_mpa"."name", ''))
                    || to_tsvector('simple_unaccent'::regconfig, COALESCE("mpa_mpa"."designation", ''))
                    || to_tsvector('simple_unaccent'::regconfig, COALESCE("mpa_mpa"."designation_eng", '')) 
                )
            );''',
            '''CREATE INDEX idx_trgm_mpa_name ON mpa_mpa USING GIN( 
                UPPER(f_unaccent(name)::text) gin_trgm_ops,
                UPPER(f_unaccent(designation)::text) gin_trgm_ops,
                UPPER(f_unaccent(designation_eng)::text) gin_trgm_ops
            );''',
        ]),
    ]
