# Generated by Django 2.0.2 on 2018-02-13 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mpa', '0007_trigram_unaccent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpa',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpa_main_set', to='mpa.Contact', verbose_name='Main Contact'),
        ),
        migrations.AlterField(
            model_name='mpa',
            name='datasource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpa_datasources', to='mpa.DataSource', verbose_name='Data Source'),
        ),
    ]
