# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-19 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpa', '0009_auto_20180918_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpa',
            name='own_type',
            field=models.CharField(blank=True, choices=[('State', 'State'), ('Communal', 'Communal'), ('Individual landowners', 'Individual landowners'), ('For-profit organisations', 'For-profit organisations'), ('Non-profit organisations', 'Non-profit organisations'), ('Joint ownership', 'Joint ownership'), ('Multiple ownership', 'Multiple ownership'), ('Contested', 'Contested'), ('Not Reported', 'Not Reported')], default='State', max_length=254, null=True, verbose_name='Ownership Type'),
        ),
        migrations.AddField(
            model_name='mpa',
            name='pa_def',
            field=models.BooleanField(default=True, verbose_name='Protected Area Definition'),
        ),
        migrations.AddField(
            model_name='mpa',
            name='verify_wdpa',
            field=models.CharField(blank=True, choices=[('Not Reported', 'Not Reported'), ('State Verified', 'State Verified'), ('Expert Verified', 'Expert Verified')], default='Not Reported', max_length=20, null=True, verbose_name='Verification by WDPA'),
        ),
        migrations.AddField(
            model_name='mpa',
            name='wdpa_metadataid',
            field=models.IntegerField(null=True, verbose_name='WDPA Source Metadata ID'),
        ),
        migrations.AddField(
            model_name='mpa',
            name='wdpa_pid',
            field=models.CharField(blank=True, help_text='WDPA Parcel ID code in form wdpaid_X. You probably should not be changing this.', max_length=52, null=True, verbose_name='WDPA Parcel ID'),
        ),
        migrations.AlterField(
            model_name='mpa',
            name='is_mpa',
            field=models.BooleanField(default=True, verbose_name='MPAtlas MPA Definition'),
        ),
        migrations.AlterField(
            model_name='mpa',
            name='mpa_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='MPA ID'),
        ),
        migrations.AlterField(
            model_name='mpa',
            name='usmpa_id',
            field=models.CharField(blank=True, help_text='US NOAA MPA Center ID. You probably should not be changing this.', max_length=50, null=True, verbose_name='US MPA ID'),
        ),
        migrations.AlterField(
            model_name='mpa',
            name='wdpa_id',
            field=models.IntegerField(blank=True, help_text='WDPA ID code. You probably should not be changing this.', null=True, verbose_name='WDPA ID'),
        ),
    ]
