# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-20 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpa', '0010_auto_20180919_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpa',
            name='calc_area_mpatlas',
            field=models.FloatField(blank=True, null=True, verbose_name='Calculated Area km² (mpatlas value)'),
        ),
        migrations.AddField(
            model_name='mpa',
            name='calc_m_area_mpatlas',
            field=models.FloatField(blank=True, null=True, verbose_name='Calculated Marine Area km² (mpatlas value)'),
        ),
        migrations.AddField(
            model_name='mpa',
            name='marine_old',
            field=models.NullBooleanField(default=True, editable=False, verbose_name='Marine (field from WDPA)'),
        ),
        migrations.AddField(
            model_name='mpa',
            name='no_take_area_mpatlas',
            field=models.FloatField(blank=True, null=True, verbose_name='No Take Area km² (mpatlas value)'),
        ),
        migrations.AddField(
            model_name='mpa',
            name='no_take_mpatlas',
            field=models.CharField(choices=[('None', 'None'), ('Part', 'Part'), ('All', 'All'), ('Not Reported', 'Not Reported')], default='Not Reported', max_length=100, verbose_name='No Take (mpatlas value)'),
        ),
        migrations.AddField(
            model_name='mpa',
            name='status_mpatlas',
            field=models.CharField(blank=True, choices=[('Proposed', 'Proposed'), ('Designated', 'Designated'), ('Defunct/Degazetted', 'Defunct/Degazetted')], default='Designated', max_length=100, null=True, verbose_name='Status (mpatlas value)'),
        ),
        migrations.AddField(
            model_name='mpa',
            name='status_year_mpatlas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Status Year (mpatlas value)'),
        ),
        migrations.AlterField(
            model_name='mpa',
            name='marine',
            field=models.IntegerField(choices=[(0, '0 - Not Marine/Unknown'), (1, '1 - Coastal/Part Marine'), (2, '2 - Full Marine')], default=0, null=True, verbose_name='Marine (field from WDPA)'),
        ),
    ]
