# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-20 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpa', '0012_remove_mpa_marine_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpa',
            name='orig_name',
            field=models.CharField(blank=True, default='', help_text='Protected area original name not including designation title', max_length=254, verbose_name='Original Name'),
        ),
    ]
