# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-21 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpa', '0013_mpa_orig_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpa',
            name='no_take_area_wdpa',
            field=models.FloatField(blank=True, null=True, verbose_name='No Take Area km² (wdpa value)'),
        ),
        migrations.AddField(
            model_name='mpa',
            name='no_take_wdpa',
            field=models.CharField(choices=[('None', 'None'), ('Part', 'Part'), ('All', 'All'), ('Not Reported', 'Not Reported'), ('Not Applicable', 'Not Applicable')], default='Not Reported', max_length=100, verbose_name='No Take (wdpa value)'),
        ),
        migrations.AlterField(
            model_name='mpa',
            name='no_take',
            field=models.CharField(choices=[('None', 'None'), ('Part', 'Part'), ('All', 'All'), ('Not Reported', 'Not Reported'), ('Not Applicable', 'Not Applicable')], default='Not Reported', max_length=100, verbose_name='No Take'),
        ),
        migrations.AlterField(
            model_name='mpa',
            name='no_take_mpatlas',
            field=models.CharField(choices=[('None', 'None'), ('Part', 'Part'), ('All', 'All'), ('Not Reported', 'Not Reported'), ('Not Applicable', 'Not Applicable')], default='Not Reported', max_length=100, verbose_name='No Take (mpatlas value)'),
        ),
    ]
