# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-30 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpa', '0014_auto_20180921_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpa',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time record created', null=True, verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='mpa',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, help_text='Date and time of last record save', null=True, verbose_name='Modification Date'),
        ),
        migrations.AlterField(
            model_name='mpa',
            name='wdpa_metadataid',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='WDPA Source Metadata ID'),
        ),
    ]
