# Generated by Django 2.2.9 on 2020-06-16 11:01

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_squashed_0002_auto_20171106_2137'),
        ('mpa', '0015_auto_20181030_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpa',
            name='implemented',
            field=models.BooleanField(blank=True, default=True, help_text='MPA is designated and implemented with regulations enforced', verbose_name='Implemented?'),
        ),
        migrations.AlterField(
            model_name='mpa',
            name='summary',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='MPA Summary Zone Description'),
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('site_id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='MPA Site ID')),
                ('wdpa_id', models.IntegerField(blank=True, help_text='WDPA ID code.', null=True, verbose_name='WDPA ID')),
                ('usmpa_id', models.CharField(blank=True, help_text='US NOAA MPA Center ID. You probably should not be changing this.', max_length=50, null=True, verbose_name='US MPA ID')),
                ('other_ids', models.CharField(blank=True, help_text='ID codes used by other groups to identify this area, e.g., TNC Caribbean or Coral Triangle Atlas ids.', max_length=1000, null=True, verbose_name='Other reference id codes')),
                ('name', models.CharField(blank=True, help_text='Protected area site name not including designation title', max_length=254, verbose_name='Name')),
                ('orig_name', models.CharField(blank=True, default='', help_text='Protected area original site name not including designation title', max_length=254, verbose_name='Original Name')),
                ('short_name', models.CharField(blank=True, help_text='Nickname if any', max_length=254)),
                ('slug', models.CharField(blank=True, help_text='URL slug string', max_length=254, verbose_name='URL Slug')),
                ('designation', models.CharField(blank=True, max_length=254, null=True, verbose_name='Designation')),
                ('designation_eng', models.CharField(blank=True, max_length=254, null=True, verbose_name='English Designation')),
                ('glores_status', models.CharField(blank=True, choices=[('', 'None'), ('nominee', 'Nominee'), ('platinum', 'Platinum Award'), ('gold', 'Gold Award'), ('silver', 'Silver Award')], default='', max_length=100, verbose_name='GLORES Status')),
                ('summary', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='MPA Summary Site Description')),
                ('categories', taggit.managers.TaggableManager(blank=True, help_text='You can assign this site to one or more categories by providing a comma-separated list of tags enclosed in quotes (e.g., [ "Shark Sanctuary", "World Heritage Site" ]', through='category.TaggedItem', to='category.Category', verbose_name='Categories')),
            ],
        ),
        migrations.AddField(
            model_name='mpa',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zones', related_query_name='zone', to='mpa.Site', verbose_name='MPA Parent Site'),
        ),
    ]
