# Generated by Django 2.2.15 on 2020-12-02 15:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpa', '0016_auto_20200616_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mpa',
            name='protection_level',
        ),
        migrations.AddField(
            model_name='mpa',
            name='fishing_protection_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, editable=False, verbose_name='Fishing Protection Level Details'),
        ),
        migrations.AddField(
            model_name='mpa',
            name='fishing_protection_level',
            field=models.CharField(blank=True, choices=[('full', 'Fully Protected'), ('high', 'Highly Protected'), ('light', 'Lightly Protected'), ('minimal', 'Minimally Protected'), ('incompatible', 'Incompatible with MPA Conservation Goals'), ('unknown', 'Unknown')], default='unknown', editable=False, max_length=100, verbose_name='Fishing Protection Level'),
        ),
        migrations.AddField(
            model_name='mpa',
            name='protection_mpaguide_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, editable=False, verbose_name='Protection Level Details - MPA Guide'),
        ),
        migrations.AddField(
            model_name='mpa',
            name='protection_mpaguide_level',
            field=models.CharField(blank=True, choices=[('full', 'Fully Protected'), ('high', 'Highly Protected'), ('light', 'Lightly Protected'), ('minimal', 'Minimally Protected'), ('incompatible', 'Incompatible with MPA Conservation Goals'), ('unknown', 'Unknown')], default='unknown', editable=False, max_length=100, verbose_name='Protection Level - MPA Guide'),
        ),
        migrations.AddField(
            model_name='mpa',
            name='protection_rbcs_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, editable=False, verbose_name='Protection Level Details - RBCS'),
        ),
        migrations.AddField(
            model_name='mpa',
            name='protection_rbcs_level',
            field=models.IntegerField(blank=True, choices=[(1, '1: No-Take/No-Go'), (2, '2: No-Take/Regulated Access'), (3, '3: No-Take/Unregulated Access'), (4, '4: Highly Regulated Extraction'), (5, '5: Moderately Regulated Extraction'), (6, '6: Weakly Regulated Extraction'), (7, '7: Very Weakly Regulated Extraction'), (8, '8: Unregulated Extraction'), (99, '99: Unknown')], default=1, editable=False, verbose_name='Protection Level - RBCS'),
        ),
        migrations.AddField(
            model_name='mpa',
            name='protection_rbcs_level_name',
            field=models.CharField(blank=True, choices=[('no-take/no-go', 'No-Take/No-Go'), ('no-take/regulated access', 'No-Take/Regulated Access'), ('no-take/unregulated access', 'No-Take/Unregulated Access'), ('highly regulated extraction', 'Highly Regulated Extraction'), ('moderately regulated extraction', 'Moderately Regulated Extraction'), ('weakly regulated extraction', 'Weakly Regulated Extraction'), ('very weakly regulated extraction', 'Very Weakly Regulated Extraction'), ('unregulated extraction', 'Unregulated Extraction'), (' unknown', ' Unknown')], default='unknown', editable=False, max_length=100, verbose_name='Protection Level Name - RBCS'),
        ),
    ]
