CREATE VIEW mpa_mpa_geom AS
 SELECT o.mpa_id,
    o.wdpa_id,
    o.usmpa_id,
    o.name,
    o.is_point,
    o.geom
   FROM mpa_mpa o
  WHERE ((o.geom IS NOT NULL) AND (o.is_point IS NOT TRUE));

CREATE VIEW mpa_mpa_point AS
 SELECT o.mpa_id,
    o.wdpa_id,
    o.usmpa_id,
    o.name,
    o.is_point,
    o.point_geom
   FROM mpa_mpa o
  WHERE ((o.point_geom IS NOT NULL) AND (o.is_point IS TRUE));

CREATE VIEW mpa_mpa_nogeom AS
 SELECT o.mpa_id,
    o.wdpa_id,
    o.usmpa_id,
    o.name,
    o.long_name,
    o.short_name,
    o.slug,
    o.country,
    o.sovereign,
    o.sub_location,
    o.designation,
    o.designation_eng,
    o.designation_type,
    o.iucn_category,
    o.int_criteria,
    o.marine,
    o.status,
    o.status_year,
    o.no_take,
    o.no_take_area,
    o.rep_m_area,
    o.calc_m_area,
    o.rep_area,
    o.calc_area,
    o.gov_type,
    o.mgmt_auth,
    o.mgmt_plan_type,
    o.mgmt_plan_ref,
    o.contact_id,
    o.conservation_effectiveness,
    o.protection_level,
    o.fishing,
    o.fishing_info,
    o.fishing_citation,
    o.access,
    o.access_citation,
    o.primary_conservation_focus,
    o.secondary_conservation_focus,
    o.tertiary_conservation_focus,
    o.conservation_focus_citation,
    o.protection_focus,
    o.protection_focus_info,
    o.protection_focus_citation,
    o.constancy,
    o.constancy_citation,
    o.permanence,
    o.permanence_citation,
    o.wdpa_notes,
    o.notes,
    o.summary,
    o.is_point,
    o.verification_state,
    o.verified_date,
    o.other_ids,
    o.verification_reason,
    o.verified_by,
    o.conservation_focus_info
   FROM mpa_mpa o;